language: objective-c

before_install:
  - brew update
  - brew install libusb --without-runtime-logging
  - brew install doxygen graphviz

branches:
  only:
    - osx

script:
  - ./autogen.sh
  - ./configure
  - make

after_success:
  - cd bbblfs-codeless-kext
  - xcodebuild build
  - pkgbuild --analyze --root ./Build/Release/ bbblfs-codeless.plist
  - pkgbuild --install-location /System/Library/Extensions --root ./Build/Release/ --scripts ./scripts --component-plist bbblfs-codeless.plist bbblfs-codeless-kext.pkg